name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_run:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '25.2.2'
        elixir-version: '1.14.3'
    - name: Install dependencies
      run: mix deps.get
    - name: Run formatter
      run: mix format --check-formatted
    - name: Build
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
